name: core_module
description: "A new Flutter project."
version: 0.0.1
homepage: https://github.com/SunnatilloShavkatov/core_module.git

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  appmetrica_plugin:
    git:
      url: https://github.com/SunnatilloShavkatov/appmetrica_plugin.git
      ref: master
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  # rest api
  dio: ^5.4.3+1
  http_parser: ^4.0.2
  # equatable
  equatable: ^2.0.5
  # hive
  hive: ^2.2.3
  # video player
  video_player_avfoundation: ^2.6.1
  video_player_platform_interface: ^6.2.2
  # youtube player
  youtube_player_iframe:
    git:
      url: https://github.com/SunnatilloShavkatov/youtube_player_iframe.git
      ref: englify
  # dropdown
  dropdown_button2: ^2.3.9
  # cached network image
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
  # file and image picker
  image_picker: ^1.1.1
  # url launchers
  url_launcher: ^6.2.6
  # box
  gap: ^3.0.1
  # firebase
  firebase_analytics: ^10.10.5

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
